language: ruby
sudo: false
rvm: 2.2.0
script: bundle exec rake deploy
env:
  global:
    secure: rCN6zutf1kK3ReGSm2RRxZw+Fg4Pd5elGB+MFScKfFj1n0QAUYbWmdm3mMsS0QSlbsJUOHqhw1SzCeB3L1wRefuDmMudxs8jzhYluOkUG3uScvfwj5s7ucySNSkWK2f4G9LhdWQ4cAtxfulJboPTHtl2ptsPAhs+1kLOS8Jep8cngiluxl4P1UcPBi6RTDUwye4neY7yVzDojvin10GPb1VKduQHrVegKQ/jrOcrzvVBzT/orXRilTk2denHq8GWgSkoTcbFQXGou6VRpUQpt3CBdGibGF7haWj7BkckHHqdTYu3zojw0oph9BP+z1yCD9aXD+S96p+1/S9kVwe8QROmQjBwg2tcIXt82fyd4J2CcORDrOw8/F5tv4JHu1LzFmYDWoXpLf9EwF80dZr23KpCzD8PG7h0TS5DQ4L1cOxm/2f2Gnyu84UMy3iJ2I4BMslwkodQbMi3+G7KD1dzo/XgWxfHCK9sQ45mNOFCtpu8E0lJUDKQ2aRA5Csmw12SghUGYeF7YuHGynWjZN/fbDrE1zynxCwLypLA0LGJP0IJVQQ/23KoFXDIZnuTGMt+miGEXn2RyaR2yF5dBuKlzFREWhgHgckFXbio9xylfEEM0Ib5tCFz70qSYUP9bwfSCeJHi/V37d2mFr++2iJKXCwyApdRkM4S+jYZ3lSjD4E=

